/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AffiliateRouteImport } from './routes/affiliate'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CartRouteImport } from './routes/cart'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SellerAuthRouteImport } from './routes/seller-auth'
import { Route as SellerDashboardRouteImport } from './routes/seller-dashboard'
import { Route as SellerGuideRouteImport } from './routes/seller-guide'
import { Route as SellerSignupRouteImport } from './routes/seller-signup'
import { Route as SellersRouteImport } from './routes/sellers'
import { Route as TermsOfServiceRouteImport } from './routes/terms-of-service'
import { Route as WishlistRouteImport } from './routes/wishlist'
import { Route as WithdrawalRouteImport } from './routes/withdrawal'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as CategorySlugRouteImport } from './routes/category/$slug'
import { Route as DanhMucSlugRouteImport } from './routes/danh-muc/$slug'
import { Route as GuidesIndexRouteImport } from './routes/guides/index'
import { Route as GuidesSlugRouteImport } from './routes/guides/$slug'
import { Route as HuongDanIndexRouteImport } from './routes/huong-dan/index'
import { Route as HuongDanSlugRouteImport } from './routes/huong-dan/$slug'
import { Route as NguoiBanIndexRouteImport } from './routes/nguoi-ban/index'
import { Route as NguoiBanSlugRouteImport } from './routes/nguoi-ban/$slug'
import { Route as PaymentCancelRouteImport } from './routes/payment/cancel'
import { Route as PaymentSuccessRouteImport } from './routes/payment/success'
import { Route as ProductSlugRouteImport } from './routes/product/$slug'
import { Route as ReadSlugRouteImport } from './routes/read/$slug'
import { Route as SanPhamSlugRouteImport } from './routes/san-pham/$slug'
import { Route as SellerSellerIdRouteImport } from './routes/seller/$sellerId'
import { Route as TagTagRouteImport } from './routes/tag/$tag'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AffiliateRoute = AffiliateRouteImport.update({
  id: '/affiliate',
  path: '/affiliate',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerAuthRoute = SellerAuthRouteImport.update({
  id: '/seller-auth',
  path: '/seller-auth',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerDashboardRoute = SellerDashboardRouteImport.update({
  id: '/seller-dashboard',
  path: '/seller-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerGuideRoute = SellerGuideRouteImport.update({
  id: '/seller-guide',
  path: '/seller-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerSignupRoute = SellerSignupRouteImport.update({
  id: '/seller-signup',
  path: '/seller-signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SellersRoute = SellersRouteImport.update({
  id: '/sellers',
  path: '/sellers',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsOfServiceRoute = TermsOfServiceRouteImport.update({
  id: '/terms-of-service',
  path: '/terms-of-service',
  getParentRoute: () => rootRouteImport,
} as any)
const WishlistRoute = WishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const WithdrawalRoute = WithdrawalRouteImport.update({
  id: '/withdrawal',
  path: '/withdrawal',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CategorySlugRoute = CategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DanhMucSlugRoute = DanhMucSlugRouteImport.update({
  id: '/danh-muc/$slug',
  path: '/danh-muc/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesIndexRoute = GuidesIndexRouteImport.update({
  id: '/guides/',
  path: '/guides/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesSlugRoute = GuidesSlugRouteImport.update({
  id: '/guides/$slug',
  path: '/guides/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const HuongDanIndexRoute = HuongDanIndexRouteImport.update({
  id: '/huong-dan/',
  path: '/huong-dan/',
  getParentRoute: () => rootRouteImport,
} as any)
const HuongDanSlugRoute = HuongDanSlugRouteImport.update({
  id: '/huong-dan/$slug',
  path: '/huong-dan/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const NguoiBanIndexRoute = NguoiBanIndexRouteImport.update({
  id: '/nguoi-ban/',
  path: '/nguoi-ban/',
  getParentRoute: () => rootRouteImport,
} as any)
const NguoiBanSlugRoute = NguoiBanSlugRouteImport.update({
  id: '/nguoi-ban/$slug',
  path: '/nguoi-ban/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentCancelRoute = PaymentCancelRouteImport.update({
  id: '/payment/cancel',
  path: '/payment/cancel',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentSuccessRoute = PaymentSuccessRouteImport.update({
  id: '/payment/success',
  path: '/payment/success',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductSlugRoute = ProductSlugRouteImport.update({
  id: '/product/$slug',
  path: '/product/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadSlugRoute = ReadSlugRouteImport.update({
  id: '/read/$slug',
  path: '/read/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SanPhamSlugRoute = SanPhamSlugRouteImport.update({
  id: '/san-pham/$slug',
  path: '/san-pham/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerSellerIdRoute = SellerSellerIdRouteImport.update({
  id: '/seller/$sellerId',
  path: '/seller/$sellerId',
  getParentRoute: () => rootRouteImport,
} as any)
const TagTagRoute = TagTagRouteImport.update({
  id: '/tag/$tag',
  path: '/tag/$tag',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/affiliate': typeof AffiliateRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/how-it-works': typeof HowItWorksRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/search': typeof SearchRoute
  '/seller-auth': typeof SellerAuthRoute
  '/seller-dashboard': typeof SellerDashboardRoute
  '/seller-guide': typeof SellerGuideRoute
  '/seller-signup': typeof SellerSignupRoute
  '/sellers': typeof SellersRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/wishlist': typeof WishlistRoute
  '/withdrawal': typeof WithdrawalRoute
  '/admin/login': typeof AdminLoginRoute
  '/category/$slug': typeof CategorySlugRoute
  '/danh-muc/$slug': typeof DanhMucSlugRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/huong-dan/$slug': typeof HuongDanSlugRoute
  '/nguoi-ban/$slug': typeof NguoiBanSlugRoute
  '/payment/cancel': typeof PaymentCancelRoute
  '/payment/success': typeof PaymentSuccessRoute
  '/product/$slug': typeof ProductSlugRoute
  '/read/$slug': typeof ReadSlugRoute
  '/san-pham/$slug': typeof SanPhamSlugRoute
  '/seller/$sellerId': typeof SellerSellerIdRoute
  '/tag/$tag': typeof TagTagRoute
  '/admin/': typeof AdminIndexRoute
  '/guides/': typeof GuidesIndexRoute
  '/huong-dan/': typeof HuongDanIndexRoute
  '/nguoi-ban/': typeof NguoiBanIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/affiliate': typeof AffiliateRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/how-it-works': typeof HowItWorksRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/search': typeof SearchRoute
  '/seller-auth': typeof SellerAuthRoute
  '/seller-dashboard': typeof SellerDashboardRoute
  '/seller-guide': typeof SellerGuideRoute
  '/seller-signup': typeof SellerSignupRoute
  '/sellers': typeof SellersRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/wishlist': typeof WishlistRoute
  '/withdrawal': typeof WithdrawalRoute
  '/admin/login': typeof AdminLoginRoute
  '/category/$slug': typeof CategorySlugRoute
  '/danh-muc/$slug': typeof DanhMucSlugRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/huong-dan/$slug': typeof HuongDanSlugRoute
  '/nguoi-ban/$slug': typeof NguoiBanSlugRoute
  '/payment/cancel': typeof PaymentCancelRoute
  '/payment/success': typeof PaymentSuccessRoute
  '/product/$slug': typeof ProductSlugRoute
  '/read/$slug': typeof ReadSlugRoute
  '/san-pham/$slug': typeof SanPhamSlugRoute
  '/seller/$sellerId': typeof SellerSellerIdRoute
  '/tag/$tag': typeof TagTagRoute
  '/admin': typeof AdminIndexRoute
  '/guides': typeof GuidesIndexRoute
  '/huong-dan': typeof HuongDanIndexRoute
  '/nguoi-ban': typeof NguoiBanIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/affiliate': typeof AffiliateRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/how-it-works': typeof HowItWorksRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/search': typeof SearchRoute
  '/seller-auth': typeof SellerAuthRoute
  '/seller-dashboard': typeof SellerDashboardRoute
  '/seller-guide': typeof SellerGuideRoute
  '/seller-signup': typeof SellerSignupRoute
  '/sellers': typeof SellersRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/wishlist': typeof WishlistRoute
  '/withdrawal': typeof WithdrawalRoute
  '/admin/login': typeof AdminLoginRoute
  '/category/$slug': typeof CategorySlugRoute
  '/danh-muc/$slug': typeof DanhMucSlugRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/huong-dan/$slug': typeof HuongDanSlugRoute
  '/nguoi-ban/$slug': typeof NguoiBanSlugRoute
  '/payment/cancel': typeof PaymentCancelRoute
  '/payment/success': typeof PaymentSuccessRoute
  '/product/$slug': typeof ProductSlugRoute
  '/read/$slug': typeof ReadSlugRoute
  '/san-pham/$slug': typeof SanPhamSlugRoute
  '/seller/$sellerId': typeof SellerSellerIdRoute
  '/tag/$tag': typeof TagTagRoute
  '/admin/': typeof AdminIndexRoute
  '/guides/': typeof GuidesIndexRoute
  '/huong-dan/': typeof HuongDanIndexRoute
  '/nguoi-ban/': typeof NguoiBanIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/affiliate'
    | '/auth'
    | '/cart'
    | '/how-it-works'
    | '/privacy-policy'
    | '/search'
    | '/seller-auth'
    | '/seller-dashboard'
    | '/seller-guide'
    | '/seller-signup'
    | '/sellers'
    | '/terms-of-service'
    | '/wishlist'
    | '/withdrawal'
    | '/admin/login'
    | '/category/$slug'
    | '/danh-muc/$slug'
    | '/guides/$slug'
    | '/huong-dan/$slug'
    | '/nguoi-ban/$slug'
    | '/payment/cancel'
    | '/payment/success'
    | '/product/$slug'
    | '/read/$slug'
    | '/san-pham/$slug'
    | '/seller/$sellerId'
    | '/tag/$tag'
    | '/admin/'
    | '/guides/'
    | '/huong-dan/'
    | '/nguoi-ban/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/affiliate'
    | '/auth'
    | '/cart'
    | '/how-it-works'
    | '/privacy-policy'
    | '/search'
    | '/seller-auth'
    | '/seller-dashboard'
    | '/seller-guide'
    | '/seller-signup'
    | '/sellers'
    | '/terms-of-service'
    | '/wishlist'
    | '/withdrawal'
    | '/admin/login'
    | '/category/$slug'
    | '/danh-muc/$slug'
    | '/guides/$slug'
    | '/huong-dan/$slug'
    | '/nguoi-ban/$slug'
    | '/payment/cancel'
    | '/payment/success'
    | '/product/$slug'
    | '/read/$slug'
    | '/san-pham/$slug'
    | '/seller/$sellerId'
    | '/tag/$tag'
    | '/admin'
    | '/guides'
    | '/huong-dan'
    | '/nguoi-ban'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/affiliate'
    | '/auth'
    | '/cart'
    | '/how-it-works'
    | '/privacy-policy'
    | '/search'
    | '/seller-auth'
    | '/seller-dashboard'
    | '/seller-guide'
    | '/seller-signup'
    | '/sellers'
    | '/terms-of-service'
    | '/wishlist'
    | '/withdrawal'
    | '/admin/login'
    | '/category/$slug'
    | '/danh-muc/$slug'
    | '/guides/$slug'
    | '/huong-dan/$slug'
    | '/nguoi-ban/$slug'
    | '/payment/cancel'
    | '/payment/success'
    | '/product/$slug'
    | '/read/$slug'
    | '/san-pham/$slug'
    | '/seller/$sellerId'
    | '/tag/$tag'
    | '/admin/'
    | '/guides/'
    | '/huong-dan/'
    | '/nguoi-ban/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AffiliateRoute: typeof AffiliateRoute
  AuthRoute: typeof AuthRoute
  CartRoute: typeof CartRoute
  HowItWorksRoute: typeof HowItWorksRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  SearchRoute: typeof SearchRoute
  SellerAuthRoute: typeof SellerAuthRoute
  SellerDashboardRoute: typeof SellerDashboardRoute
  SellerGuideRoute: typeof SellerGuideRoute
  SellerSignupRoute: typeof SellerSignupRoute
  SellersRoute: typeof SellersRoute
  TermsOfServiceRoute: typeof TermsOfServiceRoute
  WishlistRoute: typeof WishlistRoute
  WithdrawalRoute: typeof WithdrawalRoute
  AdminLoginRoute: typeof AdminLoginRoute
  CategorySlugRoute: typeof CategorySlugRoute
  DanhMucSlugRoute: typeof DanhMucSlugRoute
  GuidesSlugRoute: typeof GuidesSlugRoute
  HuongDanSlugRoute: typeof HuongDanSlugRoute
  NguoiBanSlugRoute: typeof NguoiBanSlugRoute
  PaymentCancelRoute: typeof PaymentCancelRoute
  PaymentSuccessRoute: typeof PaymentSuccessRoute
  ProductSlugRoute: typeof ProductSlugRoute
  ReadSlugRoute: typeof ReadSlugRoute
  SanPhamSlugRoute: typeof SanPhamSlugRoute
  SellerSellerIdRoute: typeof SellerSellerIdRoute
  TagTagRoute: typeof TagTagRoute
  AdminIndexRoute: typeof AdminIndexRoute
  GuidesIndexRoute: typeof GuidesIndexRoute
  HuongDanIndexRoute: typeof HuongDanIndexRoute
  NguoiBanIndexRoute: typeof NguoiBanIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/affiliate': {
      id: '/affiliate'
      path: '/affiliate'
      fullPath: '/affiliate'
      preLoaderRoute: typeof AffiliateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller-auth': {
      id: '/seller-auth'
      path: '/seller-auth'
      fullPath: '/seller-auth'
      preLoaderRoute: typeof SellerAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller-dashboard': {
      id: '/seller-dashboard'
      path: '/seller-dashboard'
      fullPath: '/seller-dashboard'
      preLoaderRoute: typeof SellerDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller-guide': {
      id: '/seller-guide'
      path: '/seller-guide'
      fullPath: '/seller-guide'
      preLoaderRoute: typeof SellerGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller-signup': {
      id: '/seller-signup'
      path: '/seller-signup'
      fullPath: '/seller-signup'
      preLoaderRoute: typeof SellerSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sellers': {
      id: '/sellers'
      path: '/sellers'
      fullPath: '/sellers'
      preLoaderRoute: typeof SellersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms-of-service': {
      id: '/terms-of-service'
      path: '/terms-of-service'
      fullPath: '/terms-of-service'
      preLoaderRoute: typeof TermsOfServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wishlist': {
      id: '/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof WishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/withdrawal': {
      id: '/withdrawal'
      path: '/withdrawal'
      fullPath: '/withdrawal'
      preLoaderRoute: typeof WithdrawalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$slug': {
      id: '/category/$slug'
      path: '/category/$slug'
      fullPath: '/category/$slug'
      preLoaderRoute: typeof CategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/danh-muc/$slug': {
      id: '/danh-muc/$slug'
      path: '/danh-muc/$slug'
      fullPath: '/danh-muc/$slug'
      preLoaderRoute: typeof DanhMucSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/': {
      id: '/guides/'
      path: '/guides'
      fullPath: '/guides/'
      preLoaderRoute: typeof GuidesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/$slug': {
      id: '/guides/$slug'
      path: '/guides/$slug'
      fullPath: '/guides/$slug'
      preLoaderRoute: typeof GuidesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/huong-dan/': {
      id: '/huong-dan/'
      path: '/huong-dan'
      fullPath: '/huong-dan/'
      preLoaderRoute: typeof HuongDanIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/huong-dan/$slug': {
      id: '/huong-dan/$slug'
      path: '/huong-dan/$slug'
      fullPath: '/huong-dan/$slug'
      preLoaderRoute: typeof HuongDanSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nguoi-ban/': {
      id: '/nguoi-ban/'
      path: '/nguoi-ban'
      fullPath: '/nguoi-ban/'
      preLoaderRoute: typeof NguoiBanIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nguoi-ban/$slug': {
      id: '/nguoi-ban/$slug'
      path: '/nguoi-ban/$slug'
      fullPath: '/nguoi-ban/$slug'
      preLoaderRoute: typeof NguoiBanSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment/cancel': {
      id: '/payment/cancel'
      path: '/payment/cancel'
      fullPath: '/payment/cancel'
      preLoaderRoute: typeof PaymentCancelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment/success': {
      id: '/payment/success'
      path: '/payment/success'
      fullPath: '/payment/success'
      preLoaderRoute: typeof PaymentSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$slug': {
      id: '/product/$slug'
      path: '/product/$slug'
      fullPath: '/product/$slug'
      preLoaderRoute: typeof ProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/read/$slug': {
      id: '/read/$slug'
      path: '/read/$slug'
      fullPath: '/read/$slug'
      preLoaderRoute: typeof ReadSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/san-pham/$slug': {
      id: '/san-pham/$slug'
      path: '/san-pham/$slug'
      fullPath: '/san-pham/$slug'
      preLoaderRoute: typeof SanPhamSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller/$sellerId': {
      id: '/seller/$sellerId'
      path: '/seller/$sellerId'
      fullPath: '/seller/$sellerId'
      preLoaderRoute: typeof SellerSellerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tag/$tag': {
      id: '/tag/$tag'
      path: '/tag/$tag'
      fullPath: '/tag/$tag'
      preLoaderRoute: typeof TagTagRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AffiliateRoute: AffiliateRoute,
  AuthRoute: AuthRoute,
  CartRoute: CartRoute,
  HowItWorksRoute: HowItWorksRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  SearchRoute: SearchRoute,
  SellerAuthRoute: SellerAuthRoute,
  SellerDashboardRoute: SellerDashboardRoute,
  SellerGuideRoute: SellerGuideRoute,
  SellerSignupRoute: SellerSignupRoute,
  SellersRoute: SellersRoute,
  TermsOfServiceRoute: TermsOfServiceRoute,
  WishlistRoute: WishlistRoute,
  WithdrawalRoute: WithdrawalRoute,
  AdminLoginRoute: AdminLoginRoute,
  CategorySlugRoute: CategorySlugRoute,
  DanhMucSlugRoute: DanhMucSlugRoute,
  GuidesSlugRoute: GuidesSlugRoute,
  HuongDanSlugRoute: HuongDanSlugRoute,
  NguoiBanSlugRoute: NguoiBanSlugRoute,
  PaymentCancelRoute: PaymentCancelRoute,
  PaymentSuccessRoute: PaymentSuccessRoute,
  ProductSlugRoute: ProductSlugRoute,
  ReadSlugRoute: ReadSlugRoute,
  SanPhamSlugRoute: SanPhamSlugRoute,
  SellerSellerIdRoute: SellerSellerIdRoute,
  TagTagRoute: TagTagRoute,
  AdminIndexRoute: AdminIndexRoute,
  GuidesIndexRoute: GuidesIndexRoute,
  HuongDanIndexRoute: HuongDanIndexRoute,
  NguoiBanIndexRoute: NguoiBanIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
