-- Add some sample products with active status
INSERT INTO products (
  title, 
  slug, 
  description, 
  short_description,
  price, 
  original_price,
  seller_id, 
  category_id, 
  status,
  google_drive_link,
  thumbnail_url,
  file_format,
  file_size,
  tags,
  images
) VALUES 
(
  'Thảo luận một số vấn đề vận dụng văn bản pháp quy triển khai Quyết định 2495/QĐ-BYT',
  'thao-luan-van-ban-phap-quy-2495',
  'Tài liệu chi tiết về việc vận dụng văn bản pháp quy trong triển khai Quyết định 2495/QĐ-BYT của Bộ Y tế. Bao gồm các hướng dẫn cụ thể, ví dụ thực tế và phân tích chuyên sâu.',
  'Hướng dẫn vận dụng văn bản pháp quy Quyết định 2495/QĐ-BYT',
  20000,
  25000,
  'e14120f3-fc99-4f8b-9f52-fa227ed1bad4',
  (SELECT id FROM categories LIMIT 1),
  'active',
  'https://drive.google.com/file/d/1ZHhorWQho7pC_75Zis21fGmXcKv_DeqreaVjuter8F4/view',
  'https://lh5.googleusercontent.com/z5wfsDfLhGGMqvHMeL1apALB4KX5w7MWYZEippue_lE6XuY6ptcbbMF5c2qPF2XfDHkR148vEKol0_U=s220',
  'PDF',
  '2.5MB',
  ARRAY['pháp quy', 'y tế', 'quyết định'],
  ARRAY['https://lh5.googleusercontent.com/z5wfsDfLhGGMqvHMeL1apALB4KX5w7MWYZEippue_lE6XuY6ptcbbMF5c2qPF2XfDHkR148vEKol0_U=s220']
),
(
  'Tài liệu hướng dẫn kỹ thuật chuyên ngành',
  'tai-lieu-huong-dan-ky-thuat',
  'Bộ tài liệu hướng dẫn kỹ thuật chuyên ngành với nội dung chi tiết, hình ảnh minh họa và ví dụ thực tế. Phù hợp cho cán bộ kỹ thuật và quản lý.',
  'Hướng dẫn kỹ thuật chuyên ngành từ A-Z',
  35000,
  45000,
  'e14120f3-fc99-4f8b-9f52-fa227ed1bad4',
  (SELECT id FROM categories LIMIT 1),
  'active',
  'https://drive.google.com/file/d/sample123/view',
  'https://via.placeholder.com/220x160/6366f1/ffffff?text=Tài+liệu',
  'DOCX',
  '5.2MB',
  ARRAY['kỹ thuật', 'hướng dẫn', 'chuyên ngành'],
  ARRAY['https://via.placeholder.com/220x160/6366f1/ffffff?text=Tài+liệu']
),
(
  'Bộ slide thuyết trình chuyên nghiệp',
  'bo-slide-thuyet-trinh',
  'Bộ sưu tập các mẫu slide thuyết trình chuyên nghiệp với thiết kế đẹp mắt, nội dung logic và dễ sử dụng. Phù hợp cho prezentation, báo cáo và đào tạo.',
  'Slide thuyết trình đẹp và chuyên nghiệp',
  50000,
  NULL,
  'e14120f3-fc99-4f8b-9f52-fa227ed1bad4',
  (SELECT id FROM categories LIMIT 1),
  'active',
  'https://drive.google.com/file/d/sample456/view',
  'https://via.placeholder.com/220x160/10b981/ffffff?text=Slides',
  'PPTX',
  '12.8MB',
  ARRAY['slide', 'thuyết trình', 'template'],
  ARRAY['https://via.placeholder.com/220x160/10b981/ffffff?text=Slides']
);